--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Março-02-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUTO
--------------------------------------------------------

  CREATE TABLE "CODFEL"."PRODUTO" 
   (	"COD_PRODUTO" NUMBER(5,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"LOCAL_IMAGEM" VARCHAR2(100 BYTE), 
	"FORNECEDOR" VARCHAR2(30 BYTE), 
	"PRECO" NUMBER(8,2), 
	"CUSTO" NUMBER(8,2), 
	"ESTOQUE" NUMBER(5,0), 
	"ESTOQUE_MIN" NUMBER(5,0), 
	"ESTOQUE_MAX" NUMBER(5,0), 
	"CATEGORIA" VARCHAR2(20 BYTE), 
	"ARTIGO" VARCHAR2(20 BYTE), 
	"MARCA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSELETRONICSSTORE" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "CODFEL"."USUARIO" 
   (	"COD" NUMBER(5,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"SOBRENOME" VARCHAR2(50 BYTE), 
	"LOCAL_IMAGEM" VARCHAR2(100 BYTE), 
	"CARGO" VARCHAR2(50 BYTE), 
	"CIDADE" VARCHAR2(20 BYTE), 
	"IDADE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSELETRONICSSTORE" ;
--------------------------------------------------------
--  Constraints for Table PRODUTO
--------------------------------------------------------

  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("ARTIGO" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("ESTOQUE" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("CUSTO" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("PRECO" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."PRODUTO" MODIFY ("COD_PRODUTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "CODFEL"."USUARIO" MODIFY ("SOBRENOME" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."USUARIO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CODFEL"."USUARIO" MODIFY ("COD" NOT NULL ENABLE);
