
--------------INICIO CRIAÇÃO DE TABELAS ---------------

CREATE TABLE PRODUTO(
  COD_PRODUTO NUMBER(8) NOT NULL,
  COD_FORNECEDOR NUMBER(8),
  COD_ARTIGO NUMBER(8),
  COD_MARCA NUMBER(8),
  COD_MARGEM NUMBER(8),
  COD_BARRAS NUMBER(30),
  ATIVO CHAR(1),
  DATA_CADASTRO DATE,
  NOME VARCHAR2(50) NOT NULL,
  DESCRICAO VARCHAR2(200),
  CUSTO NUMBER(10,2) NOT NULL,
  PRECO NUMBER(10,2),
  DESCONTO NUMBER,
  ESTOQUE NUMBER(8) NOT NULL,
  ESTOQUE_MIN NUMBER(8),
  ESTOQUE_MAX NUMBER(8),
  PESO NUMBER,
  COMPRIMENTO NUMBER,
  ALTURA NUMBER,
  LARGURA NUMBER,
  CONSTRAINT PK_PRODUTO_COD PRIMARY KEY(COD_PRODUTO)
);

CREATE TABLE CATEGORIA_PRODUTO(
  COD_CATEGORIA NUMBER(8) NOT NULL,
  DESCRICAO VARCHAR2(50) NOT NULL,
  MARGEM NUMBER,
  DESCONTO NUMBER,
  CONSTRAINT PK_CATEGORIA_PRODUTO_COD PRIMARY KEY(COD_CATEGORIA)
);
  
CREATE TABLE ARTIGO_PRODUTO(
  COD_ARTIGO NUMBER(8) NOT NULL,
  COD_CATEGORIA NUMBER(8) NOT NULL,
  DESCRICAO VARCHAR2(50) NOT NULL,
  MARGEM NUMBER,
  DESCONTO NUMBER,
  CONSTRAINT PK_ARTIGO_PRODUTO_COD PRIMARY KEY(COD_ARTIGO)
);

CREATE TABLE ESPECIFICACAO_ARTIGO(
  COD_ESPECIFICACAO_ARTIGO NUMBER(8) NOT NULL,
  COD_ESPECIFICAO NUMBER(8),
  COD_ARTIGO_PRODUTO NUMBER(8),
  CONSTRAINT PK_ESPECIFICACAO_ARTIGO_COD PRIMARY KEY(COD_ESPECIFICACAO_ARTIGO)
);

CREATE TABLE ESPECIFICACAO(
  COD_ESPECIFICACAO NUMBER(8) NOT NULL,
  DESCRICAO VARCHAR2(50),
  TIPO_VALOR CHAR(1),
  CONSTRAINT PK_ESPECIFICACAO_COD PRIMARY KEY(COD_ESPECIFICACAO)
);

CREATE TABLE PRE_ESPEC_VALOR(
  COD_PRE_ESPEC_VALOR NUMBER(8) NOT NULL,
  COD_ESPECIFICACAO NUMBER(8) NOT NULL,
  VALOR VARCHAR2(80),
  CONSTRAINT PK_PRE_ESPEC_COD PRIMARY KEY(COD_PRE_ESPEC_VALOR)
);

CREATE TABLE ESPECIFICACAO_PRODUTO(
  COD_ESPEC_PROD NUMBER(8) NOT NULL,
  COD_ESPECIFICACAO NUMBER(8),
  COD_PRODUTO NUMBER(8),
  VALOR_ESPECIFICO VARCHAR2(80),
  COD_PRE_VALOR NUMBER(8),
  CONSTRAINT PK_ESPEC_PROD_COD PRIMARY KEY(COD_ESPEC_PROD)
);

CREATE TABLE IMAGEM_PRODUTO(
  COD_IMAGEM_PRODUTO NUMBER(8) NOT NULL,
  COD_PRODUTO NUMBER(8) NOT NULL,
  LOCAL_IMAGEM VARCHAR2(100) NOT NULL,
  DESCRICAO VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_IMAGEM_PRODUTO_COD PRIMARY KEY(COD_IMAGEM_PRODUTO)
);

CREATE TABLE MARGEM_PRODUTO(
  COD_MARGEM NUMBER(8) NOT NULL,
  DESCRICAO VARCHAR2(50),
  CONSTRAINT PK_MARGEM_PRODUTO_COD PRIMARY KEY(COD_MARGEM)
);

CREATE TABLE MARCA_PRODUTO(
  COD_MARCA_PRODUTO NUMBER(8) NOT NULL,
  DESCRICAO VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_MARCA_PRODUTO_COD PRIMARY KEY(COD_MARCA_PRODUTO)
);


CREATE SEQUENCE SEQ_PRODUTO;
CREATE SEQUENCE SEQ_CATEGORIA_PRODUTO;
CREATE SEQUENCE SEQ_ARTIGO_PRODUTO;
CREATE SEQUENCE SEQ_ESPECIFICACAO_ARTIGO;
CREATE SEQUENCE SEQ_ESPECIFICACAO;
CREATE SEQUENCE SEQ_PRE_ESPEC_VALOR;
CREATE SEQUENCE SEQ_ESPECIFICACAO_PRODUTO;
CREATE SEQUENCE SEQ_IMAGEM_PRODUTO;
CREATE SEQUENCE SEQ_MARGEM_PRODUTO;
CREATE SEQUENCE SEQ_MARCA_PRODUTO;

SELECT current_value FROM sys.sequences WHERE name = 'SEQ_PRODUTO' ;

COMMIT;



















--------------   FIM CRIAÇÃO DE TABELAS ---------------
------------ADICIONANDO CHAVES ESTRANGEIRAS -----------

ALTER TABLE PRODUTOS
ADD CONSTRAINT FK_CATEGORIA_PRODUTOS_COD FOREIGN KEY(COD_CATEGORIA_PRODUTO)
REFERENCES CATEGORIA_PRODUTO(COD_CATEGORIA_PRODUTO);







--------- CRIANDO SEQUENCES -----------

CREATE SEQUENCE SEQ_COD_PRODUTO;

--------- FIM CRIANDO SEQUENCES -----------

----------- CRIANDO PROCEDURES ------------

CREATE OR REPLACE PROCEDURE CRUD_PRODUTO
(xCod_Prod number, xNome varchar, xCod_Categoria number,xCod_Fornecedor number, xPreco_Venda number, xPreco_Forn number, xQuant_Estoque number, xDescricao varchar, xOPR char)
IS 
xEXCEPTION EXCEPTION;
BEGIN IF (xOPR = 'I')THEN
INSERT INTO PRODUTOS(cod_produto, nome, cod_categoria_produto, cod_fornecedor, preco_venda, preco_forn, quant_estoque, descricao)
VALUES( xCod_Prod, xNome, xCod_Categoria,xCod_Fornecedor, xPreco_Venda, xPreco_Forn, xQuant_Estoque, xDescricao);
ELSE IF(xOPR = 'A') THEN
UPDATE PRODUTOS
SET nome = xNome, cod_categoria_produto = xCod_Categoria, cod_fornecedor = xCod_Fornecedor, preco_venda = xPreco_Venda, preco_forn = xPreco_Forn, quant_estoque = xQuant_Estoque, descricao = xDescricao
WHERE cod_produto = xCod_Prod;
ELSE IF(xOPR = 'D') THEN
DELETE FROM PRODUTOS
WHERE cod_produto =  xCod_Prod;
ELSE RAISE xEXCEPTION;
END IF;
END IF;
END IF;
END;


CREATE OR REPLACE PROCEDURE CRUD_CATEGORIA_PRODUTO
(xCod_Categoria_Produto number, xDescricao varchar, xOPR char)
IS 
xEXCEPTION EXCEPTION;
BEGIN IF (xOPR = 'I')THEN
INSERT INTO CATEGORIA_PRODUTO(cod_categoria_produto, descricao)
VALUES(xCod_Categoria_Produto , xDescricao);

ELSE IF(xOPR = 'A') THEN
UPDATE CATEGORIA_PRODUTO
SET descricao = xDescricao
WHERE cod_categoria_produto = xCod_Categoria_Produto;

ELSE IF(xOPR = 'D') THEN
DELETE FROM CATEGORIA_PRODUTO
WHERE cod_categoria_produto = xCod_Categoria_Produto;
ELSE RAISE xEXCEPTION;
END IF;
END IF;
END IF;
END;




